### ISSUE TITLE
Commenting out lines ending with opening parenthesis

### ISSUE THREAD

**Issue by bdargham** [ligasgr/intellij-xquery#138]
When commenting out a block of code, lines ending with opening parenthesis aren't closed correctly.
Here's a sample code block to comment out:
```xquery
declare function local:foobar( 
    $arg1 as xs:boolean
) as xs:string {
    ()
};
```

**Comment by ligasgr** [comment]
From what I understand it's about the fact that at the end of the first line the closing comment ':)' is added without a space in front of it to avoid treating the whole token '(:)' as beginning of another opening of comment.
Is that the case?

**Comment by bdargham** [comment]
Yes, that is precisely the problem. Thank you.

**Comment by ligasgr** [comment]
Would you expect that such a behaviour only works like this for line comments? or also for block comments?

**Comment by ligasgr** [comment]
Self-remark: This might possibly require implementing SelfManagingCommenter.

**Comment by bdargham** [comment]
I'm not sure what's best. When I want to comment out a block, e.g. an entire function, I select it and click `Cmd-/` (using Mac) which blocks it out one line at a time. Otherwise, I would need to enter `(:` at the start and `:)` at the end which is less practical. I'm not familiar with a shortcut for block commenting vs. line commenting using IntelliJ.
Would it be complicated to systematically include a space in commenting out lines? I believe that would be sufficient.

**Comment by ligasgr** [comment]
Yes, there is a shortcut for block comment and on windows it's:
ctrl-/ - line comment
ctrl-shift-/ - block comment
I don't know what it is on Mac but I think that if go here:
https://www.jetbrains.com/idea/help/keyboard-shortcuts-you-cannot-miss.html
and in top right corner pick OS X that should let you find what you're looking for.

The approach with adding that space everywhere "kind of works" in a sense that the space gets added but then uncommenting a line commented-out like that leaves that addition space hanging there even though it shouldn't be left there (that's all when using standard IDEA commenting engine).
In order to do some more advanced commenting logic I would have to completely override the whole process which is far more complicated than just adding a space to the comment suffix configuration.

Is the workaround with using block comment sufficient enough for your needs?

**Comment by bdargham** [comment]
Yes, that's fine. It's really only a minor inconvenience. And thanks for a very useful plugin. ;)
