### ISSUE TITLE
Confused string highlighting within an XML text block with {} constructs.

### ISSUE THREAD

**Issue by rhdunn** [ligasgr/intellij-xquery#168]
Given:

    declare function foo($a, $b) {
        <foo>a is '{$a}<caret></foo>
    };
    ()

Typing `'` causes the string from the inserted `'` (i.e. `'</foo>\n};\n()`) to be highlighted with the string colour.

Then typing `, b is '{$b}'` results in `', b is '` being highlighted as a string, in addition to `'</foo>\n};\n()`.

Selecting the `<foo>a is '{$a}', b is '{$b}'</foo>` line, cutting it (Ctrl+X) then pasting it (Ctrl+V) results in the correct behaviour -- the `a is '{$a}', b is '{$b}'` text is highlighted as black text on white.

Selecting that line again, then pasting the previously selected line contents (Ctrl+V) results in only `'</foo>\n};\n()` being highlighted as a string.

NOTE: The behaviour is the same when using `"` instead of `'`.

**Comment by ligasgr** [comment]
Hey,

Don't know if you are aware but according to the standard strings are mult-line in XQuery.

``` xquery
"abc
def
ghi"
```
Try this out. It works fine in any implementation.
Because of that it's impossible to handle cases like you mentioned because there is no single character that can be reasonably treated as end-of-invalid-string (like new-line in Java for example).
What I'm planning to do though is to improve automatic insertion of matching (closing) single/double quote (which doesn't work properly in all the cases).
Would that improve your situation?

**Comment by rhdunn** [comment]
From what I understand, the problem is due to the `}'` part -- that is closing the inline xquery and continuing the XML text block section. It looks like the parser is getting confused and is not doing the xquery => XML transition, so is parsing the `'` in xquery mode.

Thus, the parsing modes should look like:

    xml tag  : <foo>
    xml text : a is '
    xquery   : {$a}
    xml text : ', b is '
    xquery   : {$b}
    xml text : '
    xml tag  : </foo>

**Comment by ligasgr** [comment]
Ahh. I see your point now. Initially I missed the fact that you are inserting the closing quote in <caret>'s place.
That's definitely a bug an I'll try to fix it.
